### ISSUE TITLE
Make consul connect plugin source configurable

### ISSUE THREAD

**Issue by oschistad** [fredrikhgrelland/terraform-nomad-presto#30]
To support airgapped environments the artefact source uri for the plugin must be configurable

**Comment by zhenik** [comment]
@oschistad Could you elaborate more descriptive here? Maybe links to documentation part of prestosql

**Comment by oschistad** [comment]
This module contains an artefact stanza which pulls in the Consul Connect Native library for Presto. This stanza uses a hardcoded URL from an Internet source. 
The target environment for this module is an airgapped secure environment with no Internet access.
That means that the nomad job will fail to start due to an unreachable artefact source.

The linked patch will both make the artefact source configurable using a variable, and make the relevant template sections optional for deployments where Consul Connect is not used.
