### ISSUE TITLE
Update documentation,  distributed (cluster) mode deployment

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/terraform-nomad-presto#46]
## What is the issue?
Ref: https://github.com/fredrikhgrelland/terraform-nomad-presto#option-2-presto-and-nomad

**Verifying setup -> Option 2** does not work when deploying presto in distributed mode.
It fails on the step when the user needs to execute a command 
```
show catalogs;
```
After command `presto`

## Suggestion(s)/solution(s) [Optional]
Check the configuration of `coordinator`. 

- It might be the wrong port 8080, due to internal proxy communication
- `http` disabled, only `https`

```
node.id=3b1c9ca0-2096-9018-22c1-017d58008f1c
node.environment=presto
node.internal-address=presto


coordinator=true
node-scheduler.include-coordinator=false
discovery-server.enabled=true
discovery.uri=https://127.0.0.1:25056

dynamic.http-client.https.hostname-verification=false
failure-detector.http-client.https.hostname-verification=false
memoryManager.http-client.https.hostname-verification=false
scheduler.http-client.https.hostname-verification=false
workerInfo.http-client.https.hostname-verification=false

discovery.http-client.https.hostname-verification=false
node-manager.http-client.https.hostname-verification=false
exchange.http-client.https.hostname-verification=false


http-server.http.enabled=false
http-server.authentication.type=CERTIFICATE
# Work behind proxy
http-server.authentication.allow-insecure-over-http=true
http-server.process-forwarded=true
http-server.https.enabled=true
http-server.https.port=25056
http-server.https.keystore.path=/local/presto.pem
http-server.https.truststore.path=/local/roots.pem

# This is the same jks, but it will not do the consul connect authorization in intra cluster communication
internal-communication.https.required=true

internal-communication.shared-secret= "asdasdsadafdsa"

internal-communication.https.keystore.path=/local/presto.pem
internal-communication.https.truststore.path=/local/roots.pem

query.client.timeout=5m
query.min-expire-age=30m
query.max-memory=76MB
```

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by claesgill** [comment]
I recreated this, but in my end, it seems to work. Maybe I misunderstood something?

![presto](https://user-images.githubusercontent.com/29984156/98779792-985a9e00-23f4-11eb-986a-38acb1bc51ea.PNG)

**Comment by zhenik** [comment]
@claesgill you have run presto in `standalone` mode. This issue is relevant for distributed (`cluster`) mode.

<img width="964" alt="Screenshot 2020-11-11 at 08 51 08" src="https://user-images.githubusercontent.com/15572799/98784293-33ef0d00-23fb-11eb-915b-f2506d2174f4.png">

**Comment by claesgill** [comment]
> @claesgill you have run presto in `standalone` mode. This issue is relevant for distributed (`cluster`) mode.
> 
> <img alt="Screenshot 2020-11-11 at 08 51 08" width="964" src="https://user-images.githubusercontent.com/15572799/98784293-33ef0d00-23fb-11eb-915b-f2506d2174f4.png">

_Option 2_ specify use of `standalone`...

**Comment by zhenik** [comment]
This section was written when there was only `standalone` mode. Anyway we need an update for documentation
