### ISSUE TITLE
make-command in option #3 in verifying setup gives an error

### ISSUE THREAD

**Issue by eivindberg-skd** [fredrikhgrelland/terraform-nomad-presto#48]
## Current behaviour
I'm following the setup here: https://github.com/fredrikhgrelland/terraform-nomad-presto#option-3-local-presto-cli

```
Eivinds-MacBook-Pro:terraform-nomad-presto eivindberg$ sudo make presto-cli
Password:
Makefile:78: warning: overriding commands for target `status'
Makefile:61: warning: ignoring old commands for target `status'
make: *** No rule to make target `y', needed by `presto-cli'.  Stop.
```
Removing the :y-flag in the Makefile gives the Presto-cli, however I have no connection to Presto. 

```
Eivinds-MacBook-Pro:terraform-nomad-presto eivindberg$ sudo make presto-cli
Makefile:78: warning: overriding commands for target `status'
Makefile:61: warning: ignoring old commands for target `status'
CID=$(docker run --rm -d --network host consul:1.8 connect proxy -token master -service presto-local -upstream presto:8080)
docker run --rm -it --network host prestosql/presto:341 presto --server localhost:8080 --http-proxy localhost:8080 --catalog hive --schema default --user presto --debug
presto:default> show catalogs;
Error running command: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8080
java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8080
```

Having no connection could be related to issue #46 Update documentation, distributed mode deployment. 

The make presto-cli not working is something else. 

## Expected behaviour
To enter the CLI and being able to run a query successfully from the cli by running: 

`make presto-cli` and then the query (like SHOW CATALOGS;). 

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by claesgill** [comment]
Hey @eivindberg-skd, 

I tried recreating this issue, and in my end this works fine. I've used the following commands:
```sh
make presto-cli
presto:default> show tables;
presto:default> show catalogs;
```

**Result:**
```sh
09:29 $ make presto-cli
CID=$(docker run --rm -d --network host consul:1.8 connect proxy -token master -service presto-local -upstream presto:8080)
docker run --rm -it --network host prestosql/presto:341 presto --server localhost:8080 --http-proxy localhost:8080 --catalog hive --schema default --user presto --debug
docker rm -f $CID
Unable to find image 'prestosql/presto:341' locally
341: Pulling from prestosql/presto
75f829a71a1c: Pull complete 
826423656c28: Pull complete 
adc59b45210d: Pull complete 
a1112891496a: Pull complete 
Digest: sha256:f89b36ab70e3ca8e19661657759357565e8f98b710bd8d6b9a7e96f03c148d80
Status: Downloaded newer image for prestosql/presto:341
presto:default> show tables;
     Table     
---------------
 flattenedjson 
 iris          
 somejson      
 tweets        
(4 rows)

Query 20201105_083041_00010_dvt5u, FINISHED, 2 nodes
http://localhost:8080/ui/query.html?20201105_083041_00010_dvt5u
Splits: 19 total, 19 done (100.00%)
CPU Time: 0.0s total,   129 rows/s, 3.12KB/s, 3% active
Per Node: 0.0 parallelism,     0 rows/s,    24B/s
Parallelism: 0.0
Peak Memory: 0B
2.08 [4 rows, 99B] [1 rows/s, 48B/s]

presto:default> SHOW CATALOGS;
 Catalog 
---------
 hive    
 jmx     
 memory  
 system  
 tpcds   
 tpch    
(6 rows)

Query 20201105_083215_00011_dvt5u, FINISHED, 1 node
http://localhost:8080/ui/query.html?20201105_083215_00011_dvt5u
Splits: 19 total, 19 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 5% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 86.4KB
2.40 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> 
```

Is this still an issue for you, or can we close this issue?

**Comment by zhenik** [comment]
Docker works differently on mac. Docker runs on mac inside a virtual machine. It brings troubles especially when you want to use `--network=host` flag.

We had a discussion about it, but we had not updated Makefiles on all modules. 
Discussion https://github.com/fredrikhgrelland/vagrant-hashistack-template/pull/34#issuecomment-704391894

**Comment by claesgill** [comment]
Ok, should we update the README with information with a link to how to install the presto cli? Alternatively, I can create an `install-presto-cli` method in the `Makefile`.

What do you think, @zhenik @eivindberg-skd ?

**Comment by zhenik** [comment]
> Ok, should we update the README with information with a link to how to install the presto cli? Alternatively, I can create an `install-presto-cli` method in the `Makefile`.
> 
> What do you think, @zhenik @eivindberg-skd ?

Previously we had two commands.
1. For setup proxy via consul cli
2. Run presto cli from localmachine

**Comment by eivindberg-skd** [comment]
@claesgill  - I'm unable to reproduce this error (from VDI) after: 
- Giving my user appropriate rights to Docker
- Not using sudo (by starting from scratch and removing old boxes). (Thank you @zhenik )

From what I can gather, this issue can be closed.

**Comment by claesgill** [comment]
> @claesgill - I'm unable to reproduce this error (from VDI) after:
> 
> * Giving my user appropriate rights to Docker
> * Not using sudo (by starting from scratch and removing old boxes). (Thank you @zhenik )
> 
> From what I can gather, this issue can be closed.

Closing this issue based of the above comment.
