### ISSUE TITLE
Additional information in README.md

### ISSUE THREAD

**Issue by hannemariavister** [fredrikhgrelland/terraform-nomad-presto#60]
## What is the issue?
I miss information about how to create local proxy to presto instance to make http://localhost:8080 avaliable (presto-gui and running queries from intelliJ).

## Suggestion(s)/solution(s) [Optional]
I suggest to include information about how to create local proxy to presto instance, which is:`make proxy-presto`. The commands already exists in [Makefile](https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/Makefile#L92).

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Related https://github.com/fredrikhgrelland/terraform-nomad-presto/issues/48

**Comment by claesgill** [comment]
@hannemariavister please check out the PR regarding this issue :point_right: #72

**Comment by hannemariavister** [comment]
> @hannemariavister please check out the PR regarding this issue 👉 #72

LGTM 💯
