### ISSUE TITLE
Add `standalone` example

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/terraform-nomad-presto#61]
## What is the issue?
Add standalone example for simplification
## Suggestion(s)/solution(s) [Optional]
add new directory `example/standalone` or `example/presto_standalone`

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
working on this, but a huge blocker in https://github.com/fredrikhgrelland/terraform-nomad-hive/issues/52 atm
