### ISSUE TITLE
Add support for vault-provided credentials (and example)

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/terraform-nomad-presto#64]
## What is the issue?
Add support for fetching credentials for dependent modules from the Vault and render them directly to nomad job.

## Suggestion(s)/solution(s) [Optional]

Follow hive pr https://github.com/fredrikhgrelland/terraform-nomad-hive/pull/53 

## Optional
Creds with vault
- related https://github.com/fredrikhgrelland/terraform-nomad-minio/issues/66
- related https://github.com/fredrikhgrelland/terraform-nomad-postgres/issues/45
- related https://github.com/fredrikhgrelland/terraform-nomad-hive/issues/44

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by claesgill** [comment]
I'm not sure why we would want to do this. I mean examples of using Vault creds is present in all the modules already.

**Comment by zhenik** [comment]
> I'm not sure why we would want to do this. I mean examples of using Vault creds is present in all the modules already.

Supported:
- [X] Shared secret [ref](https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto.hcl#L323-L329)
- [ ] minio secrets [ref](https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto.hcl#L191-L192)

**Comment by claesgill** [comment]
Ahh got it, thought you meant something else. Then I agree, not sure about providing additional examples though. Should just use the ones we already have, and turning on every feature. WDYT?

It's late and I don't have my glasses, but I can't see any typos :sweat_smile:  What's the typo?

**Comment by zhenik** [comment]
<img width="777" alt="Screenshot 2020-11-11 at 18 47 01" src="https://user-images.githubusercontent.com/15572799/98845654-5100fb80-244e-11eb-9829-5886bab54b90.png">

**Comment by claesgill** [comment]
Oh, thanks! I fixed it in this PR #79
