### ISSUE TITLE
Increase memory allocation for consul sidecar proxy

### ISSUE THREAD

**Issue by gustavnordgren** [fredrikhgrelland/terraform-nomad-presto#73]
## Feature description
Increase memory allocation for presto sidecar proxy

## Why is it needed?
Proxy crashes due to beeing out of memory

## Suggestion(s)/solution(s) [Optional]
Increase memory allocation

## Definition of done
Side car proxy services are running with more memory

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Could you provide some logs or screenshots?

I see that we have a memory alloc variable for both `/conf/nomad/presto.hcl` (stands for mode `cluster`) and `/conf/nomad/presto_standalone.hcl` (stands for `stadalone` deployment).

But I see that `cpu` variable available only in `/conf/nomad/presto.hcl`, but not in `/conf/nomad/presto_standalone.hcl`

**Comment by gustavnordgren** [comment]
I am afraid logs have been purged. This behavior has only been recorded in presto_standalone.hcl
There was no recordings of running out of cpu, as you say there is no value set for memory allocation and therefore it is set to the default value: 256 Mb. At this time we have seen that this presto instance may run out of memory and with tests where memory is set to 512Mb these issues has not (yet) been prevalent.

**Comment by zhenik** [comment]
@gustavnordgren is it related issue https://github.com/fredrikhgrelland/terraform-nomad-postgres/issues/56 ?

**Comment by gustavnordgren** [comment]
@zhenik yes

**Comment by zhenik** [comment]
> @zhenik yes

Then, we might need that feature in each module
