### ISSUE TITLE
Readd healthchecks in presto_standalone example

### ISSUE THREAD

**Issue by claesgill** [fredrikhgrelland/terraform-nomad-presto#81]
## Current behaviour
No healthchecks

## Expected behaviour
Commented helathchecks should be implemented: https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto_standalone.hcl#L50-L67

## How to reproduce?
`make up-standalone`

## Suggestion(s)/solution(s) [Optional]
Maybe add a service proxie to do the checks for us.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Can I offer to add 3 health checks:
- presto-hive-availability
- presto-hive-minio
- presto-availability

These health checks will cover communication between all required services
