### ISSUE TITLE
Unable to drop/rename tables and columns in presto-standalone

### ISSUE THREAD

**Issue by hannemariavister** [fredrikhgrelland/terraform-nomad-presto#90]
## Current behaviour
I miss some parameters in presto that let me drop and rename tables. Current behavior gives me error when trying : `drop table <existing_table>`.

I am not able to add/drop/rename columns either. 

## Suggestion(s)/solution(s) [Optional]
Add the following parameters:
![image](https://user-images.githubusercontent.com/43400021/99527809-b2b8ec80-299d-11eb-8492-3f3e463fc61b.png)

The following branch solves this issue: https://github.com/hannemariavister/terraform-nomad-presto/tree/issue_90_add-parameters-to-presto

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Hive docker image uses `env` variables, which means all additional configuration could be provided as env variables to terraform see here https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/main.tf#L6.

You need to add all configuration as env variables. 
Example
```hcl
module "presto" {
  source = "../.."
  
# all required lines
  container_environment_variables = [
    "hive.allow-drop-table=true",
    "hive.allow-rename-table=true",
    # etc
  ]
}

```
